name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 194.238.19.57
          username: root
          key: ${{ secrets.VPS_KEY }}
          script: |
            /root/deploy.sh
      